// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// NOTE FOR MAINTAINERS:
// The Android block below was reconstructed from the existing Firebase
// client configuration for project `biteo-1e76d` (public client config,
// not a server secret). The application ID is changing to
// `in.biteo.vendor`, which requires a NEW Firebase Android app
// registration. After registering that app, run:
//
//     flutterfire configure -p biteo-1e76d
//
// to regenerate this file (including the correct Android appId) and to
// obtain the matching `android/app/google-services.json`.
//
// The Web app configuration could NOT be safely reconstructed (the
// registered Web app's apiKey/appId are not recoverable from this
// repository), so Web values are marked PENDING_*. Register/confirm the
// Web app in the Firebase console, then run `flutterfire configure`.
//
// iOS/macOS/Windows/Linux Firebase options are intentionally unconfigured.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration is PENDING: register a Web app in the Firebase
  // console for project `biteo-1e76d`, then run `flutterfire configure`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PENDING_WEB_API_KEY',
    appId: 'PENDING_WEB_APP_ID',
    messagingSenderId: '476619872302',
    projectId: 'biteo-1e76d',
    authDomain: 'PENDING_WEB_AUTH_DOMAIN',
    storageBucket: 'biteo-1e76d.firebasestorage.app',
    measurementId: 'G-RE5LHL0YQE',
  );

  // Android configuration reconstructed from the existing registered
  // client config for project `biteo-1e76d`. The appId reflects the
  // current (pre-rename) registration and MUST be refreshed via
  // `flutterfire configure` once the `in.biteo.vendor` Firebase Android
  // app has been registered.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApZ8m1kkZlDkyc-NmJzz3JdSd7DPt51oM',
    appId: '1:476619872302:android:06e455428e2e8e69e9e7bf',
    messagingSenderId: '476619872302',
    projectId: 'biteo-1e76d',
    storageBucket: 'biteo-1e76d.firebasestorage.app',
  );
}